[build-system]
requires = ["setuptools>=80", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "slothpy"
version = "0.4.0"
authors = [
    { name = "Mikołaj Tadeusz Żychowicz", email = "mikolaj.zychowicz@uj.edu.pl" },
]
description = "A small molecular magnetism related package."
license = { file = "LICENSE.txt" }
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "h5netcdf>=1.8.1",
    "h5py>=3.16.0",
    "marimo>=0.23.3",
    "numpy>=2.4.4",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "rich>=15.0.0",
    "scipy>=1.17.1",
    "tomli-w>=1.2.0",
    "xarray>=2026.4.0",
]

[dependency-groups]
lint = ["mypy>=1.19.1", "ruff>=0.15.8", "ty>=0.0.26"]
test = ["pytest>=9.0.3", "pytest-cov>=7.1.0"]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 88
src = ["src", "tests"]
target-version = "py314"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "B"]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = true

[tool.mypy]
plugins = ["pydantic.mypy"]
python_version = "3.14"
mypy_path = "src"
check_untyped_defs = true
warn_unused_configs = true
no_implicit_optional = true

[[tool.mypy.overrides]]
module = ["h5py", "h5py.*"]
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-vv -ra --tb=short --cov=slothpy --cov-report=term-missing"
