import math

def GEN_OH2(code, num, x, y, z, w, a, b, v):
    if code == 1:
        x[0] = 0.0
        y[0] = 0.0
        z[0] = 1.0
        w[0] = v
        num += 1
        return num

    elif code == 2:
        b = math.sqrt(1.0 - a * a)
        x[0] = a
        y[0] = b
        z[0] = 0.0
        w[0] = v
        x[1] = -a
        y[1] = b
        z[1] = 0.0
        w[1] = v
        x[2] = a
        y[2] = -b
        z[2] = 0.0
        w[2] = v
        x[3] = -a
        y[3] = -b
        z[3] = 0.0
        w[3] = v
        x[4] = b
        y[4] = a
        z[4] = 0.0
        w[4] = v
        x[5] = -b
        y[5] = a
        z[5] = 0.0
        w[5] = v
        x[6] = b
        y[6] = -a
        z[6] = 0.0
        w[6] = v
        x[7] = -b
        y[7] = -a
        z[7] = 0.0
        w[7] = v
        num += 8
        return num

    elif code == 3:
        b = math.sqrt(1.0 - a * a)
        x[0] = a
        y[0] = b
        z[0] = v
        w[0] = 2.0 * v
        x[1] = -a
        y[1] = b
        z[1] = v
        w[1] = 2.0 * v
        x[2] = a
        y[2] = -b
        z[2] = v
        w[2] = 2.0 * v
        x[3] = -a
        y[3] = -b
        z[3] = v
        w[3] = 2.0 * v
        x[4] = a
        y[4] = v
        z[4] = b
        w[4] = 2.0 * v
        x[5] = -a
        y[5] = v
        z[5] = b
        w[5] = 2.0 * v
        x[6] = a
        y[6] = v
        z[6] = -b
        w[6] = 2.0 * v
        x[7] = -a
        y[7] = v
        z[7] = -b
        w[7] = 2.0 * v
        x[8] = b
        y[8] = a
        z[8] = v
        w[8] = 2.0 * v
        x[9] = -b
        y[9] = a
        z[9] = v
        w[9] = 2.0 * v
        x[10] = b
        y[10] = -a
        z[10] = v
        w[10] = 2.0 * v
        x[11] = -b
        y[11] = -a
        z[11] = v
        w[11] = 2.0 * v
        num += 12
        return num

    elif code == 4:
        b = math.sqrt(1.0 - 2.0 * a * a)
        x[0] = a
        y[0] = a
        z[0] = b
        w[0] = 2.0 * v
        x[1] = -a
        y[1] = a
        z[1] = b
        w[1] = 2.0 * v
        x[2] = a
        y[2] = -a
        z[2] = b
        w[2] = 2.0 * v
        x[3] = -a
        y[3] = -a
        z[3] = b
        w[3] = 2.0 * v
        x[4] = a
        y[4] = b
        z[4] = a
        w[4] = 2.0 * v
        x[5] = -a
        y[5] = b
        z[5] = a
        w[5] = 2.0 * v
        x[6] = a
        y[6] = -b
        z[6] = a
        w[6] = 2.0 * v
        x[7] = -a
        y[7] = -b
        z[7] = a
        w[7] = 2.0 * v
        x[8] = b
        y[8] = a
        z[8] = a
        w[8] = 2.0 * v
        x[9] = -b
        y[9] = a
        z[9] = a
        w[9] = 2.0 * v
        x[10] = b
        y[10] = -a
        z[10] = a
        w[10] = 2.0 * v
        x[11] = -b
        y[11] = -a
        z[11] = a
        w[11] = 2.0 * v
        num += 12
        return num

    elif code == 5:
        b = math.sqrt(1.0 - a * a)
        x[0] = a
        y[0] = b
        z[0] = 0.0
        w[0] = v
        x[1] = -a
        y[1] = b
        z[1] = 0.0
        w[1] = v
        x[2] = a
        y[2] = -b
        z[2] = 0.0
        w[2] = v
        x[3] = -a
        y[3] = -b
        z[3] = 0.0
        w[3] = v
        x[4] = b
        y[4] = a
        z[4] = 0.0
        w[4] = v
        x[5] = -b
        y[5] = a
        z[5] = 0.0
        w[5] = v
        x[6] = b
        y[6] = -a
        z[6] = 0.0
        w[6] = v
        x[7] = -b
        y[7] = -a
        z[7] = 0.0
        w[7] = v
        x[8] = a
        y[8] = 0.0
        z[8] = b
        w[8] = 2.0 * v
        x[9] = -a
        y[9] = 0.0
        z[9] = b
        w[9] = 2.0 * v
        x[10] = b
        y[10] = 0.0
        z[10] = a
        w[10] = 2.0 * v
        x[11] = -b
        y[11] = 0.0
        z[11] = a
        w[11] = 2.0 * v
        x[12] = 0.0
        y[12] = a
        z[12] = b
        w[12] = 2.0 * v
        x[13] = 0.0
        y[13] = -a
        z[13] = b
        w[13] = 2.0 * v
        x[14] = 0.0
        y[14] = b
        z[14] = a
        w[14] = 2.0 * v
        x[15] = 0.0
        y[15] = -b
        z[15] = a
        w[15] = 2.0 * v
        num += 16
        return num

    elif code == 6:
        c = math.sqrt(1.0 - a * a - b * b)
        x[0] = a
        y[0] = b
        z[0] = c
        w[0] = 2.0 * v
        x[1] = -a
        y[1] = b
        z[1] = c
        w[1] = 2.0 * v
        x[2] = a
        y[2] = -b
        z[2] = c
        w[2] = 2.0 * v
        x[3] = -a
        y[3] = -b
        z[3] = c
        w[3] = 2.0 * v
        x[4] = a
        y[4] = c
        z[4] = b
        w[4] = 2.0 * v
        x[5] = -a
        y[5] = c
        z[5] = b
        w[5] = 2.0 * v
        x[6] = a
        y[6] = c
        z[6] = -b
        w[6] = 2.0 * v
        x[7] = -a
        y[7] = c
        z[7] = -b
        w[7] = 2.0 * v
        x[8] = b
        y[8] = a
        z[8] = c
        w[8] = 2.0 * v
        x[9] = -b
        y[9] = a
        z[9] = c
        w[9] = 2.0 * v
        x[10] = b
        y[10] = -a
        z[10] = c
        w[10] = 2.0 * v
        x[11] = -b
        y[11] = -a
        z[11] = c
        w[11] = 2.0 * v
        x[12] = b
        y[12] = c
        z[12] = a
        w[12] = 2.0 * v
        x[13] = -b
        y[13] = c
        z[13] = a
        w[13] = 2.0 * v
        x[14] = b
        y[14] = c
        z[14] = -a
        w[14] = 2.0 * v
        x[15] = -b
        y[15] = c
        z[15] = -a
        w[15] = 2.0 * v
        x[16] = c
        y[16] = a
        z[16] = b
        w[16] = 2.0 * v
        x[17] = -c
        y[17] = a
        z[17] = b
        w[17] = 2.0 * v
        x[18] = c
        y[18] = -a
        z[18] = b
        w[18] = 2.0 * v
        x[19] = -c
        y[19] = -a
        z[19] = b
        w[19] = 2.0 * v
        x[20] = c
        y[20] = b
        z[20] = a
        w[20] = 2.0 * v
        x[21] = -c
        y[21] = b
        z[21] = a
        w[21] = 2.0 * v
        x[22] = c
        y[22] = b
        z[22] = -a
        w[22] = 2.0 * v
        x[23] = -c
        y[23] = b
        z[23] = -a
        w[23] = 2.0 * v
        num += 24
        return num

    else:
        return num
