# SlothPy
# Copyright (C) 2025 Mikolaj Tadeusz Zychowicz (MTZ)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

[relacs]
slt_filepath = "/home/mikolaj/Sloth/Sloth/seminarium/import.slt"
number_cpus = 64

orientations = [[0,0,1,1]] # [[0,0,1,0.333333333],[1,0,0,0.333333333],[0,1,0,0.333333333]] # [[0,0,1,1]]
fields = [0.3]
temperatures = [30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50] # "np.arange(10,55,5)" # [2.5,5,7.5,10,12.5,15,17.5,20,22.5,25,27.5,30,32.5,35,37.5,40] # [5,7.5,10,12.5,15,17.5,20,22.5,25,27.5,30,32.5,35,37.5,40]
frequencies = "np.logspace(-3, 5, 300)"

states_number = 6
degeneracy_tolerance = 1e-6
psi_frequency_shift = true
initial_correlation = false
omega_loop = false
chi_s = false

n_points = [111]
q_ranges = [0.5]
broadening = "gaussian" # "gaussian" # "lorentzian" #
fwhm = [0.04]
adaptive_fwhm = false
modes_low = 1e-5
modes_high = 540
cutoff_fwhm = 1.09
qtm = true

chi_csv_path = "/home/mikolaj/Sloth/Sloth/seminarium/ac_Tb.dat"
tau_21_csv_path = "/home/mikolaj/Sloth/Sloth/seminarium/tau_R21_Tb.dat"
tau_41_csv_path = "" # "/home/mikolaj/Sloth/Sloth/seminarium/tau_R41_Tb.dat"
show_plot = true

[supercell]
xyz_path = "/home/mikolaj/Sloth/Sloth/seminarium/YCo_supercell_from_cell/dof_0_disp_0.xyz"
group_name = "YCo_supercell"
cell_params = [22.663134149075237, 22.663134149075233, 25.14851428466812, 90.0, 90.0, 120.0]
nx = 3
ny = 3
nz = 2
replace_atoms = [0]
new_atoms = ["Tb"]

[hessian]
path = "/home/mikolaj/Sloth/Sloth/seminarium/YCo_supercell_from_cell"
group_name = "YCo_hessian"
displacement_number = 1
step = 0.01
accoustic_sum_rule = "symmetric"
dos = ""

[spin_phonon]
path = "/home/mikolaj/Ac_relacs_publication/derivatives_displacements/unit_cell_0005_single/TbCo" # "/home/mikolaj/Data/Displacements_small_0001/DyCo_displ" # "/home/mikolaj/Ac_relacs_publication/derivatives_displacements/unit_cell_0005_single/DyCo" # 
group_name = "TbCo_spin_phonon"
orca_fragovl_path =  "/home/mikolaj/orca_6_1_0_avx2/orca_fragovl" # "/home/mikolaj/orca_6_1_0_avx2/orca_fragovl" #
displacement_number = 1
step = 0.0005
